apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webapp
spec:
  template:
    metadata:
      annotations: 
        autoscaling.knative.dev/min-scale: "1"
        dapr.io/config: tracing
        dapr.io/app-id: webapp
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "9099"
    spec:
      containers:
        - image: docker.io/salaboy/webapp-5dd817b6438eb2b7aec9bd0d6b49d12b@sha256:271e22ccdecd562b003c44dec5654a43cd8151f6ead5d33b8f9d7bcf8922da6d
          livenessProbe:
            httpGet:
              path: /info
              port: 0
          name: user-container
          readinessProbe:
            httpGet:
              path: /info
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100