# permissions for end users to edit conferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conference-editor-role
rules:
- apiGroups:
  - kubebuilder.conference.salaboy.com
  resources:
  - conferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebuilder.conference.salaboy.com
  resources:
  - conferences/status
  verbs:
  - get
