---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - conference.salaboy.com
  resources:
  - conferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - conference.salaboy.com
  resources:
  - conferences/finalizers
  verbs:
  - update
- apiGroups:
  - conference.salaboy.com
  resources:
  - conferences/status
  verbs:
  - get
  - patch
  - update
