apiVersion: salaboy.com/v1alpha1
kind: Environment
metadata:
  name: devenv
spec:
  compositionSelector:
    matchLabels:
      type: development
  parameters: 
    teamName: kubecon
    observabilityEnabled: false
    