apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: environments.salaboy.com
spec:
  group: salaboy.com
  names:
    kind: Environment
    plural: environments
    shortNames:
      - "env"
      - "envs"
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.parameters.teamName
      name: TEAM
      type: string
    - jsonPath: .spec.parameters.observabilityEnabled
      name: OBS
      type: boolean
    # - jsonPath: .spec.parameters.gitOpsUrl
    #   name: GITOPS
    #   type: string
    name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: 
              parameters: 
                type: object
                properties:
                  teamName:
                    type: string
                  gitOpsUrl:
                    type: string  
                  observabilityEnabled: 
                    type: boolean  
                  mockData:
                    type: boolean
                  mockUsers:
                    type: boolean  
                required: 
                - teamName 
                - observabilityEnabled   
            required: 
            - parameters          

     
            