apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: spicyprojecttemplategcps.fmtok8s.salaboy.com
spec:
  connectionSecretKeys:
    - kubeconfig
  group: fmtok8s.salaboy.com
  names:
    kind: SpicyProjectTemplateGCP
    listKind: SpicyProjectTemplateGCPList
    plural: spicyprojecttemplategcps
    singular: spicyprojectteamplategcp
    shortNames:
      - "spicy"
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A Spicy Project Template for GCP is a composite resource that represents a K8S Cluster with the components for Spicy Projects Installed
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterVersion:
                  type: string
                  description: GKE cluster version
              required:
                - clusterVersion