apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerconfig
secrets:
  - name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer
rules:
  - apiGroups: [""]
    resources: [services]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [pods]
    verbs: ["get", "list", "watch"]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: ["*"]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-deployer-staging
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: runner
    namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployer

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: staging