apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: metacontroller-conference-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: metacontroller.conference.salaboy.com/v1
    resource: conferences
  childResources:
    - apiVersion: apps/v1
      resource: deployments
  #resyncPeriodSeconds: 5
  hooks:
    sync:
      webhook:
        url: http://metacontroller-conference-controller.metacontroller.svc.cluster.local/
