fmtok8s-frontend:
  knative:
    enabled: true
  env:
    KNATIVE_ENABLED: "true"
    FRONTEND_AGENDA_SERVICE: http://fmtok8s-agenda.staging-knative.svc.cluster.local
    FRONTEND_C4P_SERVICE: http://fmtok8s-c4p.staging-knative.svc.cluster.local
    FRONTEND_EMAIL_SERVICE: http://fmtok8s-email.staging-knative.svc.cluster.local  

fmtok8s-email-service:
  knative:
    enabled: true

fmtok8s-c4p-service:
  knative:
    enabled: true
  env:
    C4P_AGENDA_SERVICE: http://fmtok8s-agenda.staging-knative.svc.cluster.local
    C4P_EMAIL_SERVICE: http://fmtok8s-email.staging-knative.svc.cluster.local  
fmtok8s-agenda-service:
  knative:
    enabled: true 
