apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositeconferenceinstances.conferences.fmtok8s.salaboy.com
  labels:
    provider: gcp
    app: fmtok8s-conference
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: conferences.fmtok8s.salaboy.com/v1alpha1
    kind: CompositeConferenceInstance
  resources:
    - name: release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations: 
            crossplane.io/external-name: conference
        spec:
          forProvider:
            chart:
              name: fmtok8s-app
              repository: https://salaboy.github.io/helm/
              version: 0.1.0
            namespace: conference
    - name: PostgreSQL
      base:
        apiVersion: db.fmtok8s.salaboy.com/v1alpha1
        kind: PostgreSQLInstance
        spec:
          forProvider:
            storageGB: 20
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storagePostgresqlGB"
          toFieldPath: "spec.forProvider.storageGB"
    - name: Redis
      base:
        apiVersion: cache.fmtok8s.salaboy.com/v1alpha1
        kind: RedisInstance
        spec:
          forProvider:
            memorySizeGb: 1
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-redis"
        - fromFieldPath: "spec.parameters.storageRedisGB"
          toFieldPath: "spec.forProvider.memorySizeGb"