apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositeconferenceinstances.conferences.fmtok8s.salaboy.com
  labels:
    provider: gcp
    app: fmtok8s-conference
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: conferences.fmtok8s.salaboy.com/v1alpha1
    kind: CompositeConferenceInstance
  resources:
    - name: release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations: 
            crossplane.io/external-name: conference
        spec:
          forProvider:
            chart:
              name: fmtok8s-app
              repository: https://salaboy.github.io/helm/
              version: 0.1.0
            namespace: conference
    - name: cloudsqlinstance
      base:
        apiVersion: database.gcp.crossplane.io/v1beta1
        kind: CloudSQLInstance
        spec:
          forProvider:
            databaseVersion: POSTGRES_9_6
            region: europe-west2
            settings:
              tier: db-custom-1-3840
              dataDiskType: PD_SSD
              ipConfiguration:
                ipv4Enabled: true
                authorizedNetworks:
                  - value: "0.0.0.0/0"
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storagePostgresqlGB"
          toFieldPath: "spec.forProvider.settings.dataDiskSizeGb"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - type: FromValue
          name: port
          value: "5432"
    - name: cloudmemorystoreinstance
      base:
        apiVersion: cache.gcp.crossplane.io/v1beta1
        kind: CloudMemorystoreInstance
        spec:
          forProvider:
            redisVersion: REDIS_5_0
            region: europe-west2
            tier: BASIC
            memorySizeGb: 1
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-redis"
        - fromFieldPath: "spec.parameters.storageRedisGB"
          toFieldPath: "spec.forProvider.settings.memorySizeGb"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - type: FromValue
          name: port
          value: "6379"