apiVersion: v1
kind: Namespace
metadata: 
  name: four-keys

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudevents-raw-endpoint-deployment
  labels:
    app: cloudevents-raw
  namespace: four-keys
spec:
  selector:
    matchLabels:
      app: cloudevents-raw
  template:
    metadata:
      labels:
        app: cloudevents-raw
    spec:
      containers:
        - name: cloudevents-endpoint
          image: ko://cloudevents-endpoint.go
          env:
          - name: POSTGRESQL_HOST
            value: postgresql
          - name: POSTGRESQL_PASS
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgres-password

---

apiVersion: v1
kind: Service
metadata:
  name: cloudevents-raw-service
  namespace: four-keys
spec:
  selector:
    app: cloudevents-raw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cdevents-translator-cronjob
  namespace: four-keys
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cdevents-translator
              image: ko://cdevents-translator.go
              imagePullPolicy: IfNotPresent
              env:
                - name: POSTGRESQL_HOST
                  value: postgresql
                - name: POSTGRESQL_PASS
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: postgres-password
          restartPolicy: OnFailure

---

 apiVersion: batch/v1
 kind: CronJob
 metadata:
   name: cdevents-deployment-frequency-cronjob
   namespace: four-keys
 spec:
   schedule: "* * * * *"
   jobTemplate:
     spec:
       template:
         spec:
           containers:
             - name: cdevents-deployment-frequency
               image: ko://cdevents-deployment-frequency.go
               imagePullPolicy: IfNotPresent
               env:
                 - name: POSTGRESQL_HOST
                   value: postgresql
                 - name: POSTGRESQL_PASS
                   valueFrom:
                     secretKeyRef:
                       name: postgresql
                       key: postgres-password
           restartPolicy: OnFailure
