apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: conferenceclusters.example.crossplane.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: example.crossplane.io
  names:
    kind: ConferenceCluster
    listKind: ConferenceClusterList
    plural: conferenceclusters
    singular: conferencecluster
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A ConferenceCluster is a composite resource that represents a K8S Cluster with the Conference Platofmr Installed
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterVersion:
                  type: string
                  description: GKE cluster version
              required:
                - clusterVersion