apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: email-service
spec:
  template:
    spec:
      containers:
        - image: salaboy/fmtok8s-email-rest:0.1.0-improved
          imagePullPolicy: Always
          env: 
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: VERSION
            value: 0.1.0  
  traffic: 
  - percent: 80
    revisionName: email-service-00001
  - latestRevision: true
    percent: 20