apiVersion: v2
name: conference
description: Conference Application
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: fmtok8s-frontend
  version: v0.1.1
  repository: https://salaboy.github.io/helm/  
- name: fmtok8s-agenda-service
  version: v0.1.1
  repository: https://salaboy.github.io/helm/
- name: fmtok8s-c4p-service
  version: v0.1.0
  repository: https://salaboy.github.io/helm/  
- name: fmtok8s-email-service
  version: v0.1.0 
  repository: https://salaboy.github.io/helm/
- name: kube-prometheus
  repository: https://charts.bitnami.com/bitnami
  condition: prometheus.enabled
  version: 8.0.8
- name: grafana-operator
  repository: https://charts.bitnami.com/bitnami
  version: 2.6.4
  condition: grafana.enabled  
