apiVersion: v2
name: conference
description: Conference Application
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: fmtok8s-agenda-service
  version: 0.1.0 
  repository: https://salaboy.github.io/helm/
