
prometheus:
  enabled: true
kube-prometheus:
  prometheus:
    service:
      type: LoadBalancer
      ports: 
        http: 80
fmtok8s-frontend:  
  prometheus:
    enabled: true
fmtok8s-agenda-service:
  prometheus:
    enabled: true
fmtok8s-email-service:
  prometheus:
    enabled: true
fmtok8s-c4p-service:
  prometheus:
    enabled: true      
